language: python
python:
  - "3.5"
notifications:
  email:
    on_success: never
    on_failure: never
  slack: huckley:RH9dq9u04SKLALXK6EQa0mkp
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: pytest