language: python
python:
  - "3.5"
notifications:
  email:
    on_success: never
    on_failure: never
#  slack: huckley:XufS5mf1g1GF3MjqPMVVcyAB
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: pytest